services:
  # Standard GUI Version (Recommended for local testing)
  vla-task:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    container_name: vla-task-container
    runtime: nvidia
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics
      - OLLAMA_HOST=http://127.0.0.1:11434
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOME}/.Xauthority:/root/.Xauthority:ro
      - /app/src/__pycache__
      - /app/starter_code/__pycache__
    ipc: host
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  